# Generated by Django 3.1.8 on 2021-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0018_auto_20210420_2016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="afatlink",
            name="hash",
            field=models.CharField(
                db_index=True, help_text="The fatlinks hash", max_length=254
            ),
        ),
    ]
