# Generated by Django 3.1.8 on 2021-05-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0014_auto_20210105_1413'),
        ('afat', '0019_add_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afat',
            name='afatlink',
            field=models.ForeignKey(help_text='The fatlink the character registered at', on_delete=django.db.models.deletion.CASCADE, related_name='afats', to='afat.afatlink'),
        ),
        migrations.AlterField(
            model_name='afat',
            name='character',
            field=models.ForeignKey(help_text='Character who registered this fat', on_delete=django.db.models.deletion.CASCADE, related_name='afats', to='eveonline.evecharacter'),
        ),
    ]
